name: Generate Snake Animation

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_PATH: dist/github-contribution-grid-snake.svg
          # (Opcional) Configure a cor da cobra e do fundo
          SNAKE_COLOR: "github_dark"
          BACKGROUND_COLOR: "transparent"
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/github-contribution-grid-snake.svg'
          message: "Atualizar animação da cobra de commits"
          signoff: false
